[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
build-mode = "module"
excluded-patches = "'Disable fullscreen ambient mode' 'GmsCore support' 'Open links externally' 'Disable zoom haptics'"
patcher-args = "-OdarkThemeBackgroundColor=@android:color/system_neutral1_900 -OlightThemeBackgroundColor=@android:color/system_neutral1_50 "

[Infinity]
apkmirror-dlurl = "https://www.apkmirror.com/apk/docile-alligator/infinity-for-reddit"
arch = "arm64-v8a"
build-mode = "module"
patcher-args = "-Oclient-id=9-0tamLtjbNmW6BbLUILlA "

